dataset: Tiny
res: 64
model: ConvNetD4
device: [0,1]

ipc: 1
syn_steps: 20
expert_epochs: 2
lr_img: 1000
lr_teacher: 0.01
buffer_path: /home/uqbyuan3/data_distillation/data/buffers_sam
data_path: /home/uqbyuan3/data_distillation/data/tiny-imagenet-200_new
ema_decay: 0.9995
Iteration: 10000
batch_syn: 300

# wandb
project: DATM_quant_Tiny

num_eval: 3
eval_it: 500
skip_first_eva: True

lr_y: 10.0
Momentum_y: 0.9
threshold: 1.
pix_init: graphcut
expansion_end_epoch: 3000
batch_train: 128
min_start_epoch: 0
current_max_start_epoch: 3
max_start_epoch: 10
lr_lr: 0.0001

zca: False

